package database

import (
	"context"
	"fmt"
	"log"

	"github.com/jackc/pgx/v5/pgxpool"
)

// RunMigrations creates the database schema if it doesn't exist.
// Called on startup from main.go. Uses a PostgreSQL advisory lock so that
// concurrent processes (api + worker) don't race.
func RunMigrations(ctx context.Context, pool *pgxpool.Pool) error {
	log.Println("Running database migrations...")

	// Acquire a session-level advisory lock so only one process runs migrations at a time.
	conn, err := pool.Acquire(ctx)
	if err != nil {
		return fmt.Errorf("acquire connection: %w", err)
	}
	defer conn.Release()

	const lockID = 1 // arbitrary but fixed
	if _, err := conn.Exec(ctx, "SELECT pg_advisory_lock($1)", lockID); err != nil {
		return fmt.Errorf("acquire migration lock: %w", err)
	}
	defer conn.Exec(ctx, "SELECT pg_advisory_unlock($1)", lockID)

	for _, migration := range migrations {
		if _, err := conn.Exec(ctx, migration); err != nil {
			return fmt.Errorf("migration failed: %w", err)
		}
	}

	log.Println("Migrations complete")
	return nil
}

var migrations = []string{
	// Cached workflow state for public consumption
	`CREATE TABLE IF NOT EXISTS company_workflows (
		id                   TEXT PRIMARY KEY,
		company_name         TEXT NOT NULL,
		slug                 TEXT UNIQUE NOT NULL,
		started_at           TIMESTAMPTZ NOT NULL,
		status               TEXT NOT NULL DEFAULT 'active',
		elapsed_days         INTEGER DEFAULT 0,
		outreach_count       INTEGER DEFAULT 0,
		restart_count        INTEGER DEFAULT 0,
		current_contact_role TEXT,
		meeting_booked_at    TIMESTAMPTZ,
		last_snapshot_at     TIMESTAMPTZ,
		updated_at           TIMESTAMPTZ DEFAULT NOW()
	)`,

	// Sanitized activity feed for public display
	`CREATE TABLE IF NOT EXISTS activity_feed (
		id          SERIAL PRIMARY KEY,
		workflow_id TEXT NOT NULL REFERENCES company_workflows(id),
		timestamp   TIMESTAMPTZ NOT NULL,
		event_type  TEXT NOT NULL,
		description TEXT NOT NULL,
		channel     TEXT,
		created_at  TIMESTAMPTZ DEFAULT NOW()
	)`,

	// Add public_id column for opaque public-facing URLs
	`ALTER TABLE company_workflows ADD COLUMN IF NOT EXISTS public_id TEXT UNIQUE DEFAULT gen_random_uuid()::TEXT`,
	`UPDATE company_workflows SET public_id = gen_random_uuid()::TEXT WHERE public_id IS NULL`,

	// Full agent suggestions (admin only)
	`CREATE TABLE IF NOT EXISTS agent_suggestions (
		id            SERIAL PRIMARY KEY,
		workflow_id   TEXT NOT NULL REFERENCES company_workflows(id),
		task_type     TEXT NOT NULL,
		request       TEXT,
		response      TEXT,
		draft_message TEXT,
		created_at    TIMESTAMPTZ DEFAULT NOW()
	)`,

	// Multi-contact tracking
	`ALTER TABLE company_workflows ADD COLUMN IF NOT EXISTS contact_count INTEGER DEFAULT 0`,

	// Admin authentication
	`CREATE TABLE IF NOT EXISTS admin_users (
		id            SERIAL PRIMARY KEY,
		email         TEXT UNIQUE NOT NULL,
		password_hash TEXT NOT NULL,
		created_at    TIMESTAMPTZ DEFAULT NOW()
	)`,

	`CREATE TABLE IF NOT EXISTS admin_sessions (
		token      TEXT PRIMARY KEY,
		user_id    INTEGER NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
		created_at TIMESTAMPTZ DEFAULT NOW(),
		expires_at TIMESTAMPTZ NOT NULL
	)`,

	`CREATE INDEX IF NOT EXISTS idx_admin_sessions_expires_at ON admin_sessions(expires_at)`,

	// DB-primary admin detail: persist full workflow state to avoid Temporal queries on page load.
	`ALTER TABLE company_workflows ADD COLUMN IF NOT EXISTS agent_task_in_progress BOOLEAN DEFAULT FALSE`,
	`ALTER TABLE company_workflows ADD COLUMN IF NOT EXISTS meeting_notes TEXT DEFAULT ''`,

	// One-time cleanup of old table names from prior migrations.
	`DROP TABLE IF EXISTS contacts CASCADE`,
	`DROP TABLE IF EXISTS outreach_attempts CASCADE`,
	`DROP SEQUENCE IF EXISTS contacts_id_seq`,
	`DROP SEQUENCE IF EXISTS outreach_attempts_id_seq`,

	`CREATE TABLE IF NOT EXISTS workflow_contacts (
		id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		workflow_id TEXT NOT NULL REFERENCES company_workflows(id) ON DELETE CASCADE,
		name        TEXT NOT NULL,
		role        TEXT NOT NULL DEFAULT '',
		linkedin    TEXT NOT NULL DEFAULT '',
		active      BOOLEAN NOT NULL DEFAULT TRUE,
		added_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
		UNIQUE (workflow_id, name)
	)`,

	`CREATE TABLE IF NOT EXISTS workflow_outreach_attempts (
		id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
		workflow_id TEXT NOT NULL REFERENCES company_workflows(id) ON DELETE CASCADE,
		timestamp   TIMESTAMPTZ NOT NULL,
		channel     TEXT NOT NULL,
		notes       TEXT NOT NULL DEFAULT '',
		contact     TEXT NOT NULL DEFAULT '',
		created_at  TIMESTAMPTZ DEFAULT NOW()
	)`,
	`CREATE INDEX IF NOT EXISTS idx_workflow_outreach_attempts_wf ON workflow_outreach_attempts(workflow_id)`,

	`ALTER TABLE agent_suggestions ADD COLUMN IF NOT EXISTS contact_name TEXT DEFAULT ''`,
	`ALTER TABLE agent_suggestions ADD COLUMN IF NOT EXISTS timestamp TIMESTAMPTZ DEFAULT NOW()`,
}
